### ISSUE TITLE
glob() finds gml-files twice

### ISSUE THREAD

**Issue by felix-mu** [tum-gis/CityGML2OBJv2#4]
On my Windows machine with Python 3.10 I found that gml-files of the input directory are processed twice since the glob() function does not appear to be case in-sensitive and identifies identical gml-files twice when checking first on "\*.gml" and then on "\*.GML":
https://github.com/tum-gis/CityGML2OBJv2/blob/c55356ab74606e9802ffa390bed7ac1953596c79/CityGML2OBJs.py#L348-L351

**Comment by ThomasFroech** [comment]
Hi, thank you for pointing this out. If my understanding is correct, modifying the types would solve the issue. Would you agree?

**Comment by felix-mu** [comment]
Yes you are right. My quick fix was to simply remove the upper case types. But did not test it with upper case file extensions so far

**Comment by ThomasFroech** [comment]
I have tested it and have not encountered any issues related to this change so far. I think that it solves the issue and I am therefore going to incorporate your approach. Thank you very much for your help!
