### ISSUE TITLE
Readme: pdf link to paper not working

### ISSUE THREAD

**Issue by maynouf** [tum-gis/CityGML2OBJv2#5]
Hello, just wanted to give you a thumbs up for such a great work while pointing out a very minor thing; apparently the link to the paper in pdf format in the `Credits` section (`http://filipbiljecki.com/publications/Biljecki2015vk.pdf`) is not working. At a quick glance it seems it should point to another path in the author's website (`https://filipbiljecki.com/publications/2015_udmv_citygml_obj.pdf`)--might do a PR late to fix it.

**Comment by ThomasFroech** [comment]
Hi, thank you for pointing this out! I adapted the link and think it should work now.
